### ISSUE TITLE
PBR latex looks too much like plastic

### ISSUE THREAD

**Issue by XiaoTDM** [LtxProgrammer/Changed-Minecraft-Mod#1084]
Enabled "Changed_PBR" resource pack and used ComplementaryReimagined Shader:
It's not goo but plastic. Is there any way to implement latex material? 
![image](https://github.com/user-attachments/assets/52b46981-94cc-49a2-95c6-111df9e9dbe1)

**Comment by LtxProgrammer** [comment]
Please refrain from "stuttering" in the issue title. Give it a proper title such as "PBR latex looks too much like plastic."

I used BSL when designing the specular textures, and I think the materials look good with BSL. Normal maps you take a longer time to develop per entity than specular, and such wasn't a goal for 0.14.

If you have any advice on how you would improve the material, please post so.

**Comment by XiaoTDM** [comment]
Is it possible for Iris/Oculus shaders to set roughness of material surface? Or reduce surface reflective strength in some other way, perhaps better.

**Comment by XiaoTDM** [comment]
I found a very important problem:
The blue channel in the PBR material does not control the reflectivity, but the luminosity.
As a result, the previously drawn materials were all incorrect, using them would cause the latex to glow eerily at night.
In addition, the red channel controls roughness, and after testing, the higher the value, the stronger the reflection, and the lower the reflection, the weaker the reflection.
After my testing, the red tones of 154 (body), 136 (hair) (terrestrial), 222 (body), 162 (hair) (aquatic) are more appropriate.

**Comment by LtxProgrammer** [comment]
Excerpt from [LabPBR Material Standard](https://shaderlabs.org/wiki/LabPBR_Material_Standard):

<html><body>
<h2><span class="mw-headline" id="Specular_Texture_(_s)">Specular Texture (_s)</span></h2>
<p>Note that your shader pack is only required to correctly read the 
smoothness (red) and F0 (green) data to be LabPBR-ready. The other 
specified datasets are optional components. More details about that can 
be found in the <a href="https://shaderlabs.org/wiki/LabPBR_Implementation_Requirements" title="LabPBR Implementation Requirements">LabPBR Implementation Requirements</a>.
</p>
<h3><span class="mw-headline" id="Red_Channel">Red Channel</span></h3>
<ul><li>Represents "perceptual" smoothness.
<ul><li>Convert perceptual smoothness to linear roughness with <code>roughness = pow(1.0 - perceptualSmoothness, 2.0)</code>.</li>
<li>Convert linear roughness to perceptual smoothness with <code>perceptualSmoothness = 1.0 - sqrt(roughness)</code>.</li></ul></li></ul>
<p><br>
<b>For Texture Artists</b><br>
A value of 255 (100%) results in a very smooth material (e.g. polished 
granite). A value of 0 (0%) creates a rough material (e.g. rocks).
</p>
<h3><span class="mw-headline" id="Green_Channel">Green Channel</span></h3>
<ul><li>Values from 0 to 229 represent F0, also known as reflectance.
<ul><li>This attribute is stored linearly. Please note that a value of 
229 represents exactly 229 divided by 255, or approximately 90%, instead
 of 100%.</li></ul></li>
<li>Values from 230 to 255 represent various different metals.
<ul><li>Details about this range is provided below.</li></ul></li></ul>
<p><br>
<b>For Texture Artists</b><br>
This can be described as the minimal reflection strength of the 
material. So a low F0 value results in a less intense reflection when 
looking directly at the material while a higher F0 value causes a 
stronger and more visible reflection. Unlike traditional specularity 
however this is not a multiplier for the reflection strength, meaning 
that reflections at flat angles will always be stronger (called 
"Fresnel", more information about that here: <a rel="nofollow" class="external text" href="https://www.researchgate.net/figure/Principle-of-the-Fresnel-effect-the-amount-of-reflection-on-a-reflective-surface-depends_fig3_319178578">Principle of the Fresnel Effect</a>).
</p>
<h3><span class="mw-headline" id="Blue_Channel">Blue Channel</span></h3>
<ul><li>On dielectrics:
<ul><li>Values from 0 to 64 represent porosity. Examples of the porosity effect can be found <a rel="nofollow" class="external text" href="https://github.com/rre36/lab-pbr/wiki/Porosity-Examples">here</a>.</li>
<li>Values from 65 to 255 represent subsurface scattering.</li>
<li>Both porosity and subsurface scattering are stored linearly.</li></ul></li>
<li>On metals/conductors:
<ul><li>Reserved for future use.</li></ul></li></ul>
<p><br>
<b>For Texture Artists</b><br>
The porosity value describes how much water a material can absorb. This 
manifests in the color of the material getting darker and less 
reflective when wet. This allows for a much more accurate behavior with 
shader packs supporting both porosity and weather based wetness (e.g. 
puddles). Below are some example values.
</p>

Material | Porosity Value
-- | --
Sand | 64
Wool | 38
Wood | 12
Metals and other impermeable materials | 0


<p>Examples of the porosity effect in action can be found <a rel="nofollow" class="external text" href="https://github.com/rre36/lab-pbr/wiki/Porosity-Examples">here</a>.
</p>
<h3><span class="mw-headline" id="Alpha_Channel">Alpha Channel</span></h3>
<ul><li>It can have values ranging from 0 to 254; 0 being 0% emissiveness and 254 being 100%.</li>
<li>This is stored linearly.</li></ul>
<p><br>
<b>For Texture Artists</b><br>
The lower the value the less light it will emit, the higher the more 
luminescent it'll be, but never use a value of 255 since this will cause
 it to be ignored.
</p>
</body>
</html>

**Comment by LtxProgrammer** [comment]
In practice this boils down to:

**Red** - Roughness (how blurry reflected light is)
**Green** - F0/Reflectance (at what angle is the material reflective
**Blue** - Subsurface scattering (how much light penetrates through the material)
**Alpha** - Emissive (how much light does the material emit)

**Comment by XiaoTDM** [comment]
It's built for LabPBR?
Sorry I was negligent.

**Comment by LtxProgrammer** [comment]
Stale issue
