### ISSUE TITLE
/curepale Doesn't work (And some other bugs)

### ISSUE THREAD

**Issue by Y1rd** [LtxProgrammer/Changed-Minecraft-Mod#1134]
Pretty much the title.
/setpaleexposure 0 works however.

Also, while on the same note. High pale exposure acts weird, and while in this state, having absorption hearts prevents the player from receiving latex attacks while not having high pale exposure does not tank it.

**Comment by LtxProgrammer** [comment]
Humans cannot be cured, and such `Pale.tryCure()` checks if the player is transfurred. This is a good example of #1076, as that isn't explained by the mod, nor the command. `Pale.tryCure()` sets the player's exposure to a negative number, which has a special case that the player will never build exposure, nor expose others.

It would probably make sense however for the command to reset exposure, instead of just only running `Pale.tryCure()`.

**Comment by Y1rd** [comment]
Huh, I swear I posted like two videos of that second bug here, but otherwise yeah.

**Comment by Y1rd** [comment]
https://github.com/user-attachments/assets/27c024ac-02f7-40e1-a773-a1ab45da638d

**Comment by LtxProgrammer** [comment]
The tryTransfur function will check the player's i-frames in a similar manner that normal damage does. You would experience the same phenomenon under the effects of poison II.
