### ISSUE TITLE
Blindness from Certain Forms does not hide Distant Horizon Chunks

### ISSUE THREAD

**Issue by Y1rd** [LtxProgrammer/Changed-Minecraft-Mod#1147]
Regular Blindness does hide the chunks correctly.
![image](https://github.com/user-attachments/assets/43269218-cc61-433b-9b85-9740773c3759)

**Comment by XiaoTDM** [comment]
DH decides whether to hide LOD chunks by determining whether a player is carrying the blindness effect.
However, these forms of blindness are not caused by potion effects (although consistent with potions), so DH does not consider the player to be blind and continues to render LOD chunks.
This issue is even more noticeable when Fog Culling is enabled in Sodium. In addition, "No Fog" is still in effect for this type of blindness.
I think you can also go to DH and create this issue (Not on GitHub).

**Comment by LtxProgrammer** [comment]
[MinecraftRenderWrapper.java:118](https://gitlab.com/distant-horizons-team/distant-horizons/-/blob/main/common/src/main/java/com/seibel/distanthorizons/common/wrappers/minecraft/MinecraftRenderWrapper.java#L118) checks the entity's effect map for the blindness key. Changed only edits `hasEffect` and `getEffect` to make the effect a permanent part of the player.
