### ISSUE TITLE
Problem with OPTIFINE

### ISSUE THREAD

**Issue by uran-nn** [LtxProgrammer/Changed-Minecraft-Mod#913]
On version Changed-m1.18.2-v0.13.1, the game crashes with (OptiFine_1.18.2_HD_U_H9)... :(

**Comment by gengyoubo** [comment]
Not compatible with OPTIFINE!

**Comment by gengyoubo** [comment]
> 在版本 Changed-m1.18.2-v0.13.1 中，游戏因 (OptiFine_1.18.2_HD_U_H9) 崩溃... :(

He said he wouldn't fix it!

**Comment by LtxProgrammer** [comment]
Do not use optifine. Use embeddium and oculus instead.

**Comment by WorkableLukica** [comment]
While it's easy to say to just use Embeddium instead of Optifine,it's a bandaid solution to some of us with weaker devices. Optifine's rendering helped me a lot more with the issues i had regarding chunk generation/rendering unlike with Embeddium,where no matter what options i chose i'd still be much more laggier than if i were using Optifine,_on servers as well_.Oculus on the other hand has it's own incompatibilities and bugs,which makes even more problems.And working forward to then add back the nice visual features that Optifine also provided.. Well,that didn't help with me needing to trial test even more mods together.I hope some sort of a fix can be implemented later on throughout development,in the foreseeable updates,though it's understandable to see the frustration with working around Optifine due to it's direct meddling with Minecraft's core code and modifications it applies.

**Comment by gengyoubo** [comment]
Did you have to add it? Can't you if you don't?

**Comment by LtxProgrammer** [comment]
I'm not fixing Optifine.

**Comment by spacedan228** [comment]
a lot of mods have problem with optifine, usually it's hard or even impossible to fix, and this mod is not an exception
